
Currently Loaded Modules:
  1) tools/miniconda/python3.8/4.9.2

 

WARNING: overwriting environment variables set in the machine
overwriting variable nnUNet_raw_data_base nnUNet_preprocessed RESULTS_FOLDER OUTPUT
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 120, in main
    task = convert_id_to_task_name(task_id)
  File "/home/smaijer/code/nnUNet/nnunet/utilities/task_name_id_conversion.py", line 47, in convert_id_to_task_name
    raise RuntimeError("More than one task name found for task id %d. Please correct that. (I looked in the "
RuntimeError: More than one task name found for task id 501. Please correct that. (I looked in the following folders:
/exports/lkeb-hpc/smaijer/data/nnUNet_raw_data_base/nnUNet_raw_data
/exports/lkeb-hpc/smaijer/data/nnUNet_preprocessed
/exports/lkeb-hpc/smaijer/data/nnUNet_raw_data_base/nnUNet_cropped_data
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 120, in main
    task = convert_id_to_task_name(task_id)
  File "/home/smaijer/code/nnUNet/nnunet/utilities/task_name_id_conversion.py", line 47, in convert_id_to_task_name
    raise RuntimeError("More than one task name found for task id %d. Please correct that. (I looked in the "
RuntimeError: More than one task name found for task id 501. Please correct that. (I looked in the following folders:
/exports/lkeb-hpc/smaijer/data/nnUNet_raw_data_base/nnUNet_raw_data
/exports/lkeb-hpc/smaijer/data/nnUNet_preprocessed
/exports/lkeb-hpc/smaijer/data/nnUNet_raw_data_base/nnUNet_cropped_data
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 120, in main
    task = convert_id_to_task_name(task_id)
  File "/home/smaijer/code/nnUNet/nnunet/utilities/task_name_id_conversion.py", line 47, in convert_id_to_task_name
    raise RuntimeError("More than one task name found for task id %d. Please correct that. (I looked in the "
RuntimeError: More than one task name found for task id 501. Please correct that. (I looked in the following folders:
/exports/lkeb-hpc/smaijer/data/nnUNet_raw_data_base/nnUNet_raw_data
/exports/lkeb-hpc/smaijer/data/nnUNet_preprocessed
/exports/lkeb-hpc/smaijer/data/nnUNet_raw_data_base/nnUNet_cropped_data
