
Currently Loaded Modules:
  1) system/python/3.10.2

 

/var/spool/slurmd/job11449071/slurm_script: line 38: conda: command not found
  Running command git clone -q https://github.com/FabianIsensee/hiddenlayer.git /tmp/pip-install-0dy48he0/hiddenlayer_de8d05ce8cc849fbb7a911c86d762a2e
  Running command git checkout -b more_plotted_details --track origin/more_plotted_details
  Switched to a new branch 'more_plotted_details'
  Branch 'more_plotted_details' set up to track remote branch 'more_plotted_details' from 'origin'.
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the '/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/python -m pip install --upgrade pip' command.
ERROR: ditable is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the '/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/python -m pip install --upgrade pip' command.
/var/spool/slurmd/job11449071/slurm_script: line 45: [: ==: unary operator expected
/home/smaijer/code/nnUNet/nnunet/training/network_training/nnUNetTrainer.py:729: RuntimeWarning: invalid value encountered in double_scalars
  global_dc_per_class = [i for i in [2 * i / (2 * i + j + k) for i, j, k in
/home/smaijer/code/nnUNet/nnunet/evaluation/evaluator.py:381: RuntimeWarning: Mean of empty slice
  all_scores["mean"][label][score] = float(np.nanmean(all_scores["mean"][label][score]))
Exception in thread Thread-4 (results_loop):
Traceback (most recent call last):
  File "/share/software/system/python/3.10.2/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-5 (results_loop):
Traceback (most recent call last):
  File "/share/software/system/python/3.10.2/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/share/software/system/python/3.10.2/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/share/software/system/python/3.10.2/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    self._target(*self._args, **self._kwargs)
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full
/home/smaijer/code/nnUNet/nnunet/training/network_training/nnUNetTrainer.py:729: RuntimeWarning: invalid value encountered in double_scalars
  global_dc_per_class = [i for i in [2 * i / (2 * i + j + k) for i, j, k in
slurmstepd: error: *** JOB 11449071 ON res-hpc-lkeb09 CANCELLED AT 2022-08-12T09:19:49 ***
