environment: line 17: /usr/share/lmod/lmod/libexec/lmod: No such file or directory
environment: line 17: /usr/share/lmod/lmod/libexec/lmod: No such file or directory
environment: line 17: /usr/share/lmod/lmod/libexec/lmod: No such file or directory
/var/spool/slurmd/job12605337/slurm_script: line 38: conda: command not found
  Running command git clone -q https://github.com/FabianIsensee/hiddenlayer.git /tmp/pip-install-y9qgptww/hiddenlayer_907f8c29a5914a52aff59d8df456af05
  Running command git checkout -b more_plotted_details --track origin/more_plotted_details
  Switched to a new branch 'more_plotted_details'
  Branch 'more_plotted_details' set up to track remote branch 'more_plotted_details' from 'origin'.
WARNING: You are using pip version 21.2.4; however, version 22.3 is available.
You should consider upgrading via the '/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/python -m pip install --upgrade pip' command.
ERROR: ditable is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
WARNING: You are using pip version 21.2.4; however, version 22.3 is available.
You should consider upgrading via the '/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/python -m pip install --upgrade pip' command.
/var/spool/slurmd/job12605337/slurm_script: line 88: /exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train: Permission denied
/var/spool/slurmd/job12605337/slurm_script: line 89: /exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train: Permission denied
/var/spool/slurmd/job12605337/slurm_script: line 90: /exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train: Permission denied
/var/spool/slurmd/job12605337/slurm_script: line 94: nnUNet_determine_postprocessing: command not found
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/home/smaijer/code/nnUNet/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/home/smaijer/code/nnUNet/nnunet/inference/predict.py", line 678, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/home/smaijer/code/nnUNet/nnunet/inference/predict.py", line 191, in predict_cases
    trainer, params = load_model_and_checkpoint_files(model, folds, mixed_precision=mixed_precision,
  File "/home/smaijer/code/nnUNet/nnunet/training/model_restore.py", line 147, in load_model_and_checkpoint_files
    all_params = [torch.load(i, map_location=torch.device('cpu')) for i in all_best_model_files]
  File "/home/smaijer/code/nnUNet/nnunet/training/model_restore.py", line 147, in <listcomp>
    all_params = [torch.load(i, map_location=torch.device('cpu')) for i in all_best_model_files]
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/lib/python3.10/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/lib/python3.10/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/results/nnUNet/3d_fullres/Task601/nnUNetTrainerV2__nnUNetPlansv2.1/fold_1/model_final_checkpoint.model'
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/home/smaijer/code/nnUNet/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/home/smaijer/code/nnUNet/nnunet/inference/predict.py", line 678, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/home/smaijer/code/nnUNet/nnunet/inference/predict.py", line 191, in predict_cases
    trainer, params = load_model_and_checkpoint_files(model, folds, mixed_precision=mixed_precision,
  File "/home/smaijer/code/nnUNet/nnunet/training/model_restore.py", line 147, in load_model_and_checkpoint_files
    all_params = [torch.load(i, map_location=torch.device('cpu')) for i in all_best_model_files]
  File "/home/smaijer/code/nnUNet/nnunet/training/model_restore.py", line 147, in <listcomp>
    all_params = [torch.load(i, map_location=torch.device('cpu')) for i in all_best_model_files]
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/lib/python3.10/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/lib/python3.10/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/results/nnUNet/3d_fullres/Task601/nnUNetTrainerV2__nnUNetPlansv2.1/fold_1/model_final_checkpoint.model'
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_evaluate_folder", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_evaluate_folder')())
  File "/home/smaijer/code/nnUNet/nnunet/evaluation/evaluator.py", line 483, in nnunet_evaluate_folder
    return evaluate_folder(args.ref, args.pred, args.l)
  File "/home/smaijer/code/nnUNet/nnunet/evaluation/evaluator.py", line 456, in evaluate_folder
    assert all([i in files_pred for i in files_gt]), "files missing in folder_with_predictions"
AssertionError: files missing in folder_with_predictions
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_evaluate_folder", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_evaluate_folder')())
  File "/home/smaijer/code/nnUNet/nnunet/evaluation/evaluator.py", line 483, in nnunet_evaluate_folder
    return evaluate_folder(args.ref, args.pred, args.l)
  File "/home/smaijer/code/nnUNet/nnunet/evaluation/evaluator.py", line 456, in evaluate_folder
    assert all([i in files_pred for i in files_gt]), "files missing in folder_with_predictions"
AssertionError: files missing in folder_with_predictions
